using Microsoft.Data.Sqlite;
using Vega.Data.MasterLibrary.Database;
using Vega.Models.MasterLibrary;
namespace Vega.Data.MasterLibrary.Repository;
public sealed class PackageTechnologyRepository
{
 public List<PackageTechnologyProfile> GetProfiles(int packageId){using var c=MasterLibraryConnection.Create();using var q=c.CreateCommand();q.CommandText="SELECT Id,PackageDefinitionId,ProfileName,Revision,IsDefault,IsActive,SourceType,SourceName,SourceReference,CreatedAt,UpdatedAt,Notes FROM PackageTechnologyProfile WHERE PackageDefinitionId=$id ORDER BY Revision";q.Parameters.AddWithValue("$id",packageId);using var r=q.ExecuteReader();var list=new List<PackageTechnologyProfile>();while(r.Read())list.Add(new PackageTechnologyProfile{Id=r.GetInt32(0),PackageDefinitionId=r.GetInt32(1),ProfileName=r.GetString(2),Revision=r.GetInt32(3),IsDefault=r.GetBoolean(4),IsActive=r.GetBoolean(5),SourceType=r.GetString(6),SourceName=r.GetString(7),SourceReference=r.GetString(8),CreatedAt=DateTime.Parse(r.GetString(9)),UpdatedAt=DateTime.Parse(r.GetString(10)),Notes=r.GetString(11)});return list;}
 public PackageTechnologyProfile? GetDefaultProfile(int id)=>GetProfiles(id).FirstOrDefault(x=>x.IsDefault);
 public PackageTechnologyProfile CreateProfile(PackageTechnologyProfile p){using var c=MasterLibraryConnection.Create();using var tx=c.BeginTransaction();if(p.IsDefault)SetDefault(c,tx,p.PackageDefinitionId,0);using var q=c.CreateCommand();q.Transaction=tx;q.CommandText="INSERT INTO PackageTechnologyProfile(PackageDefinitionId,ProfileName,Revision,IsDefault,IsActive,SourceType,SourceName,SourceReference,CreatedAt,UpdatedAt,Notes)VALUES($p,$n,$r,$d,$a,$st,$sn,$sr,$c,$u,$no);SELECT last_insert_rowid();";q.Parameters.AddWithValue("$p",p.PackageDefinitionId);q.Parameters.AddWithValue("$n",p.ProfileName);q.Parameters.AddWithValue("$r",p.Revision);q.Parameters.AddWithValue("$d",p.IsDefault);q.Parameters.AddWithValue("$a",p.IsActive);q.Parameters.AddWithValue("$st",p.SourceType);q.Parameters.AddWithValue("$sn",p.SourceName);q.Parameters.AddWithValue("$sr",p.SourceReference);q.Parameters.AddWithValue("$c",DateTime.UtcNow.ToString("O"));q.Parameters.AddWithValue("$u",DateTime.UtcNow.ToString("O"));q.Parameters.AddWithValue("$no",p.Notes);p.Id=Convert.ToInt32(q.ExecuteScalar());tx.Commit();return p;}
 public void SetDefaultProfile(int packageId,int profileId){using var c=MasterLibraryConnection.Create();using var tx=c.BeginTransaction();SetDefault(c,tx,packageId,profileId);tx.Commit();} static void SetDefault(SqliteConnection c,SqliteTransaction tx,int packageId,int profileId){using var q=c.CreateCommand();q.Transaction=tx;q.CommandText="UPDATE PackageTechnologyProfile SET IsDefault=CASE WHEN Id=$profile THEN 1 ELSE 0 END WHERE PackageDefinitionId=$package";q.Parameters.AddWithValue("$profile",profileId);q.Parameters.AddWithValue("$package",packageId);q.ExecuteNonQuery();}
 public PackageStencilRule? GetStencilRule(int profileId){using var c=MasterLibraryConnection.Create();using var q=c.CreateCommand();q.CommandText="SELECT Id,TechnologyProfileId,ApertureShape,WindowPaneEnabled FROM PackageStencilRule WHERE TechnologyProfileId=$id";q.Parameters.AddWithValue("$id",profileId);using var r=q.ExecuteReader();return r.Read()?new PackageStencilRule{Id=r.GetInt32(0),TechnologyProfileId=r.GetInt32(1),ApertureShape=r.GetString(2),WindowPaneEnabled=r.GetBoolean(3)}:null;}
 public PackageAoiRule? GetAoiRule(int profileId)=>null; public PackagePlacementRule? GetPlacementRule(int profileId)=>null;
}
