using System.Xml.Linq;
using Vega.Models;
using Vega.Models.MasterLibrary;
namespace Vega.Mirtec;
public sealed class MirtecMmdProject { public string ProjectName {get;set;}=""; public List<MirtecMmdPart> Parts {get;}=[]; }
public sealed class MirtecMmdPart { public string RefDes {get;set;}="";public string PartNumber {get;set;}="";public string Comment {get;set;}="";public double X {get;set;}public double Y{get;set;}public double Rotation{get;set;}public string Side{get;set;}="Top";public string PackageName{get;set;}="";public string LibraryUse{get;set;}="";public string LibraryPath{get;set;}="";public string MirtecAoiClass{get;set;}="";public ProjectComponentRecognitionStatus RecognitionStatus{get;set;} }
public sealed class MirtecMmdValidationResult { public int MatchedCount{get;set;}public int ManualCount{get;set;}public int NotFoundCount{get;set;}public int AmbiguousCount{get;set;}public bool IsValid=>NotFoundCount==0&&AmbiguousCount==0;public List<string> Errors{get;}=[]; }
public sealed class MirtecMmdGenerationResult { public bool Success{get;set;}public string OutputPath{get;set;}="";public int ComponentCount{get;set;}public int MatchedCount{get;set;}public int ManualCount{get;set;}public int SkippedCount{get;set;}public List<string> Errors{get;}=[];public List<string> Warnings{get;}=[];public List<MirtecMmdPart> Preview{get;}=[];public string ReportText{get;set;}=""; }
public sealed class MirtecMmdGenerator
{
 public MirtecMmdValidationResult Validate(IEnumerable<ProjectComponent> components){var r=new MirtecMmdValidationResult();foreach(var c in components){switch(c.RecognitionStatus){case ProjectComponentRecognitionStatus.Matched:r.MatchedCount++;break;case ProjectComponentRecognitionStatus.Manual:r.ManualCount++;break;case ProjectComponentRecognitionStatus.NotFound:r.NotFoundCount++;r.Errors.Add($"{c.RefDes}: NOT FOUND");break;case ProjectComponentRecognitionStatus.Ambiguous:r.AmbiguousCount++;r.Errors.Add($"{c.RefDes}: AMBIGUOUS");break;}}return r;}
 public MirtecMmdGenerationResult Generate(string projectName,IEnumerable<ProjectComponent> components,IEnumerable<PackageDefinition> packages){var list=components.ToList();var validation=Validate(list);var result=new MirtecMmdGenerationResult{MatchedCount=validation.MatchedCount,ManualCount=validation.ManualCount,SkippedCount=validation.NotFoundCount+validation.AmbiguousCount};if(!validation.IsValid){result.Errors.AddRange(validation.Errors);result.ReportText=BuildReport(list,[]);return result;}var lookup=packages.ToDictionary(p=>p.Id);var project=new MirtecMmdProject{ProjectName=projectName};foreach(var c in list){if(c.PackageDefinitionId is not int id||!lookup.TryGetValue(id,out var package)){result.Errors.Add($"{c.RefDes}: PackageDefinition is missing.");continue;}project.Parts.Add(new MirtecMmdPart{RefDes=c.RefDes,PartNumber=c.PartNumber,Comment=c.Comment,X=c.X,Y=c.Y,Rotation=NormalizeRotation(c.Rotation),Side=c.Side,PackageName=package.PackageName,LibraryUse=package.MirtecAoiClass,LibraryPath=package.MirtecAoiClass,MirtecAoiClass=package.MirtecAoiClass,RecognitionStatus=c.RecognitionStatus});}result.ComponentCount=project.Parts.Count;result.Preview.AddRange(project.Parts);result.ReportText=BuildReport(list,project.Parts);result.Success=result.Errors.Count==0;return result;}
 public static double NormalizeRotation(double value){var result=value%360;if(result<0)result+=360;return result;}
 private static string BuildReport(IEnumerable<ProjectComponent> source,IEnumerable<MirtecMmdPart> parts){var map=parts.ToDictionary(p=>p.RefDes,StringComparer.OrdinalIgnoreCase);return string.Join(Environment.NewLine,source.Select(c=>map.TryGetValue(c.RefDes,out var p)?$"{p.RefDes} | {p.PartNumber} | {p.PackageName} | {p.RecognitionStatus}":$"{c.RefDes} | {c.PartNumber} | NOT FOUND | ERROR"));}
}
public sealed class MirtecMmdRecord { public int Index {get;set;} public string X {get;set;}="0"; public string Y {get;set;}="0"; public string Rotation {get;set;}="0"; public string PartNumber {get;set;}=""; public string RefDes {get;set;}=""; public string? PackageName {get;set;} }
public sealed class MirtecMmdTemplate { public string Fid1X {get;set;}="0"; public string Fid1Y {get;set;}="0"; public string Fid2X {get;set;}="0"; public string Fid2Y {get;set;}="0"; public string CoordinateTransform {get;set;}="NO"; public List<MirtecMmdRecord> Records {get;}=[]; }
public sealed class MirtecMmdTemplateReader
{
 public MirtecMmdTemplate Read(string fileName){var template=new MirtecMmdTemplate();foreach(var line in File.ReadLines(fileName)){if(line.StartsWith("Fid1_X="))template.Fid1X=line[(line.IndexOf('=')+1)..].Trim();else if(line.StartsWith("Fid1_Y="))template.Fid1Y=line[(line.IndexOf('=')+1)..].Trim();else if(line.StartsWith("Fid2_X="))template.Fid2X=line[(line.IndexOf('=')+1)..].Trim();else if(line.StartsWith("Fid2_Y="))template.Fid2Y=line[(line.IndexOf('=')+1)..].Trim();else if(line.StartsWith("Coordinate Transform="))template.CoordinateTransform=line[(line.IndexOf('=')+1)..].Trim();else if(line.StartsWith('#')){var eq=line.IndexOf('=');var values=line[(eq+1)..].Split('\t');if(values.Length>=6)template.Records.Add(new MirtecMmdRecord{Index=int.Parse(line[1..eq]),X=values[0],Y=values[1],Rotation=values[2],PartNumber=values[3],RefDes=values[4],PackageName=values[5]=="null"?null:values[5]});}}return template;}
}
public sealed class MirtecMmdWriter
{
 public void Write(MirtecMmdProject project,string outputPath,MirtecMmdTemplate? template=null){template??=new MirtecMmdTemplate();var lines=new List<string>{"[Fiducial]",$"Fid1_X= {template.Fid1X}",$"Fid1_Y= {template.Fid1Y}",$"Fid2_X= {template.Fid2X}",$"Fid2_Y= {template.Fid2Y}","[Part Info]",$"Coordinate Transform={template.CoordinateTransform}",$"Part Count={project.Parts.Count}"};for(var i=0;i<project.Parts.Count;i++){var p=project.Parts[i];var x=p.X.ToString(System.Globalization.CultureInfo.InvariantCulture);var y=p.Y.ToString(System.Globalization.CultureInfo.InvariantCulture);var rotation=p.Rotation.ToString(System.Globalization.CultureInfo.InvariantCulture);lines.Add($"#{i+1:00000000}={x}\t{y}\t{rotation}\t{p.PartNumber}\t{p.RefDes}\t{(string.IsNullOrWhiteSpace(p.PackageName)?"null":p.PackageName)}");}File.WriteAllLines(outputPath,lines);File.WriteAllLines(Path.Combine(Path.GetDirectoryName(outputPath)!,"PROJECT_MMD_REPORT.txt"),project.Parts.Select(p=>$"{p.RefDes} | {p.PartNumber} | {p.PackageName} | {p.RecognitionStatus}"));}
}