<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Vega.StencilInput\Vega.StencilInput.csproj" />
    <ProjectReference Include="..\Vega.CAD\Vega.CAD.csproj" />
    <ProjectReference Include="..\Vega.Gerber\Vega.Gerber.csproj" />
    <ProjectReference Include="..\Vega.PnP\Vega.PnP.csproj" />
    <ProjectReference Include="..\Vega.StencilCAM\Vega.StencilCAM.csproj" />
    <ProjectReference Include="..\Vega.StencilViewer\Vega.StencilViewer.csproj" />
    <ProjectReference Include="..\Vega.Services\Vega.Services.csproj" />
    <ProjectReference Include="..\Vega.Models\Vega.Models.csproj" />
  </ItemGroup>
</Project>