-- Nominal EIA/JIS LxW package sizes. Height is a nominal library value; series-specific tolerance is noted per package.
CREATE TEMP TABLE IF NOT EXISTS ChipSeed(PackageName TEXT,ComponentType TEXT,Length REAL,Width REAL,Height REAL,Metric TEXT);
DELETE FROM ChipSeed;
INSERT INTO ChipSeed VALUES
('R01005','Resistor',0.40,0.20,0.15,'0402'),('R0201','Resistor',0.60,0.30,0.23,'0603'),('R0402','Resistor',1.00,0.50,0.35,'1005'),('R0603','Resistor',1.60,0.80,0.55,'1608'),('R0805','Resistor',2.00,1.25,0.55,'2012'),('R1206','Resistor',3.20,1.60,0.55,'3216'),('R1210','Resistor',3.20,2.50,0.55,'3225'),('R1812','Resistor',4.50,3.20,0.60,'4532'),('R2010','Resistor',5.00,2.50,0.60,'5025'),('R2512','Resistor',6.30,3.20,0.60,'6332'),
('C01005','Capacitor',0.40,0.20,0.15,'0402'),('C0201','Capacitor',0.60,0.30,0.23,'0603'),('C0402','Capacitor',1.00,0.50,0.55,'1005'),('C0603','Capacitor',1.60,0.80,0.80,'1608'),('C0805','Capacitor',2.00,1.25,0.85,'2012'),('C1206','Capacitor',3.20,1.60,0.85,'3216'),('C1210','Capacitor',3.20,2.50,0.85,'3225'),('C1812','Capacitor',4.50,3.20,0.90,'4532'),('C2220','Capacitor',5.70,5.00,1.00,'5750'),
('L0201','Inductor',0.60,0.30,0.30,'0603'),('L0402','Inductor',1.00,0.50,0.55,'1005'),('L0603','Inductor',1.60,0.80,0.80,'1608'),('L0805','Inductor',2.00,1.25,1.00,'2012'),('L1206','Inductor',3.20,1.60,1.00,'3216'),('L1210','Inductor',3.20,2.50,1.00,'3225');
UPDATE PackageDefinition SET DisplayName=PackageName,StandardName=PackageName,PackageFamily='CHIP',ComponentType=(SELECT ComponentType FROM ChipSeed s WHERE s.PackageName=PackageDefinition.PackageName),Length=(SELECT Length FROM ChipSeed s WHERE s.PackageName=PackageDefinition.PackageName),Width=(SELECT Width FROM ChipSeed s WHERE s.PackageName=PackageDefinition.PackageName),Height=(SELECT Height FROM ChipSeed s WHERE s.PackageName=PackageDefinition.PackageName),BodyLength=(SELECT Length FROM ChipSeed s WHERE s.PackageName=PackageDefinition.PackageName),BodyWidth=(SELECT Width FROM ChipSeed s WHERE s.PackageName=PackageDefinition.PackageName),PadCount=2,LeadCount=0,IPCName='CHIP',JEDECName=(SELECT Metric FROM ChipSeed s WHERE s.PackageName=PackageDefinition.PackageName),YamahaName='',MirtecAoiClass=upper((SELECT ComponentType FROM ChipSeed s WHERE s.PackageName=PackageDefinition.PackageName)),Description='Standard CHIP package',Notes='Nominal EIA/JIS body dimensions; height is nominal and manufacturer-series dependent.' WHERE PackageName IN (SELECT PackageName FROM ChipSeed);
INSERT OR IGNORE INTO PackageDefinition(PackageName,DisplayName,StandardName,PackageFamily,ComponentType,CategoryId,FamilyId,Length,Width,Height,BodyLength,BodyWidth,PadCount,LeadCount,IPCName,JEDECName,MirtecAoiClass,Description,Notes,IsActive,CreatedAt,UpdatedAt) SELECT s.PackageName,s.PackageName,s.PackageName,'CHIP',s.ComponentType,c.Id,f.Id,s.Length,s.Width,s.Height,s.Length,s.Width,2,0,'CHIP',s.Metric,upper(s.ComponentType),'Standard CHIP package','Nominal EIA/JIS body dimensions; height is nominal and manufacturer-series dependent.',1,datetime('now'),datetime('now') FROM ChipSeed s JOIN PackageCategory c ON c.Code='PASSIVE' JOIN PackageFamily f ON f.CategoryId=c.Id AND f.Code='CHIP';
-- Prefix-specific aliases deliberately avoid generic imperial aliases shared by R/C/L.
INSERT INTO MasterLibrary_PackageAliases(PackageId,Alias,AliasType,Source) SELECT p.Id,lower(substr(p.PackageName,1,1))||'_'||substr(p.PackageName,2),'Footprint','CHIP seed 019' FROM PackageDefinition p WHERE p.PackageName IN (SELECT PackageName FROM ChipSeed) AND NOT EXISTS(SELECT 1 FROM MasterLibrary_PackageAliases a WHERE a.PackageId=p.Id AND lower(a.Alias)=lower(lower(substr(p.PackageName,1,1))||'_'||substr(p.PackageName,2)));
INSERT INTO MasterLibrary_PackageAliases(PackageId,Alias,AliasType,Source) SELECT p.Id,CASE substr(p.PackageName,1,1) WHEN 'R' THEN 'RES'||substr(p.PackageName,2) WHEN 'C' THEN 'CAP'||substr(p.PackageName,2) ELSE 'IND'||substr(p.PackageName,2) END,'Footprint','CHIP seed 019' FROM PackageDefinition p WHERE p.PackageName IN (SELECT PackageName FROM ChipSeed) AND NOT EXISTS(SELECT 1 FROM MasterLibrary_PackageAliases a WHERE a.PackageId=p.Id AND lower(a.Alias)=lower(CASE substr(p.PackageName,1,1) WHEN 'R' THEN 'RES'||substr(p.PackageName,2) WHEN 'C' THEN 'CAP'||substr(p.PackageName,2) ELSE 'IND'||substr(p.PackageName,2) END));
INSERT INTO MasterLibrary_PackageAliases(PackageId,Alias,AliasType,Source) SELECT p.Id,CASE substr(p.PackageName,1,1) WHEN 'R' THEN 'RESC' WHEN 'C' THEN 'CAPC' ELSE 'INDC' END||s.Metric,'Metric','CHIP seed 019' FROM PackageDefinition p JOIN ChipSeed s ON s.PackageName=p.PackageName WHERE NOT EXISTS(SELECT 1 FROM MasterLibrary_PackageAliases a WHERE a.PackageId=p.Id AND lower(a.Alias)=lower(CASE substr(p.PackageName,1,1) WHEN 'R' THEN 'RESC' WHEN 'C' THEN 'CAPC' ELSE 'INDC' END||s.Metric));
DROP TABLE ChipSeed;
