-- Standard geometry only. A zero numeric value / empty YamahaName means "not specified".
-- Manufacturer package drawing is required for height, lead and exposed-pad geometry.
UPDATE PackageDefinition SET PackageName='QFN032P050W500', DisplayName='QFN032P050W500', StandardName='QFN 32 0.50 mm 5.0 mm', PackageFamily='QFN', ComponentType='IC', BodyLength=5.00, BodyWidth=5.00, Length=5.00, Width=5.00, Height=0, LeadCount=32, PadCount=32, Pitch=0.50, LeadLength=0, LeadWidth=0, ThermalPadLength=0, ThermalPadWidth=0, YamahaName='', MirtecAoiClass='IC_QFN', Description='32-pin QFN, 0.50 mm pitch, 5.0 mm body', Notes='Height, exposed pad and land-pattern dimensions require the component-specific package drawing.' WHERE PackageName='QFN32P050W500' AND NOT EXISTS(SELECT 1 FROM PackageDefinition WHERE PackageName='QFN032P050W500');
UPDATE PackageDefinition SET DisplayName=PackageName, ComponentType='IC', Height=0, LeadLength=0, LeadWidth=0, ThermalPadLength=0, ThermalPadWidth=0, YamahaName=CASE WHEN PackageName IN ('SO08P127W078','SSOP80P065W140','TSOP28P127W112V2','QFP032P065W092') THEN YamahaName ELSE '' END, MirtecAoiClass=CASE WHEN PackageFamily='QFN' THEN 'IC_QFN' WHEN PackageFamily='SON' THEN 'IC_SON' ELSE 'IC_LEADED' END, Notes='Height, lead and thermal-pad geometry require the component-specific package drawing.' WHERE PackageName IN ('SO08P127W078','SSOP80P065W140','TSOP28P127W112V2','QFP032P065W092','QFN032P050W500');
INSERT INTO MasterLibrary_PackageAliases(PackageId,Alias,AliasType,Source) SELECT Id,'SO-8','JEDEC','IC seed 021' FROM PackageDefinition WHERE PackageName='SO08P127W078' AND NOT EXISTS(SELECT 1 FROM MasterLibrary_PackageAliases a WHERE a.PackageId=PackageDefinition.Id AND lower(a.Alias)=lower('SO-8'));
INSERT INTO MasterLibrary_PackageAliases(PackageId,Alias,AliasType,Source) SELECT Id,'SOIC-8','JEDEC','IC seed 021' FROM PackageDefinition WHERE PackageName='SO08P127W078' AND NOT EXISTS(SELECT 1 FROM MasterLibrary_PackageAliases a WHERE a.PackageId=PackageDefinition.Id AND lower(a.Alias)=lower('SOIC-8'));
INSERT INTO MasterLibrary_PackageAliases(PackageId,Alias,AliasType,Source) SELECT Id,'QFN-32','JEDEC','IC seed 021' FROM PackageDefinition WHERE PackageName='QFN032P050W500' AND NOT EXISTS(SELECT 1 FROM MasterLibrary_PackageAliases a WHERE a.PackageId=PackageDefinition.Id AND lower(a.Alias)=lower('QFN-32'));
INSERT INTO MasterLibrary_PackageAliases(PackageId,Alias,AliasType,Source) SELECT Id,'MLF32','Industry','IC seed 021' FROM PackageDefinition WHERE PackageName='QFN032P050W500' AND NOT EXISTS(SELECT 1 FROM MasterLibrary_PackageAliases a WHERE a.PackageId=PackageDefinition.Id AND lower(a.Alias)=lower('MLF32'));
INSERT INTO MasterLibrary_PackageAliases(PackageId,Alias,AliasType,Source) SELECT Id,'VQFN32','Industry','IC seed 021' FROM PackageDefinition WHERE PackageName='QFN032P050W500' AND NOT EXISTS(SELECT 1 FROM MasterLibrary_PackageAliases a WHERE a.PackageId=PackageDefinition.Id AND lower(a.Alias)=lower('VQFN32'));
