-- Confirmed foundation: package name encodes nominal diameter x height in millimetres.
CREATE TEMP TABLE IF NOT EXISTS SpecialPassiveSeed(PackageName TEXT,BodyLength REAL,BodyWidth REAL,Height REAL);
DELETE FROM SpecialPassiveSeed;
INSERT INTO SpecialPassiveSeed VALUES ('ALC5-7.0H',5.00,5.00,7.00),('ALC6.3-7.7H',6.30,6.30,7.70),('ALC8-10.2H',8.00,8.00,10.20),('ALC10-10.2H',10.00,10.00,10.20);
UPDATE PackageDefinition SET DisplayName=PackageName,StandardName=PackageName,PackageFamily='ALUMINUM_CAP',ComponentType='Capacitor',Length=(SELECT BodyLength FROM SpecialPassiveSeed s WHERE s.PackageName=PackageDefinition.PackageName),Width=(SELECT BodyWidth FROM SpecialPassiveSeed s WHERE s.PackageName=PackageDefinition.PackageName),BodyLength=(SELECT BodyLength FROM SpecialPassiveSeed s WHERE s.PackageName=PackageDefinition.PackageName),BodyWidth=(SELECT BodyWidth FROM SpecialPassiveSeed s WHERE s.PackageName=PackageDefinition.PackageName),Height=(SELECT Height FROM SpecialPassiveSeed s WHERE s.PackageName=PackageDefinition.PackageName),LeadCount=2,PadCount=2,Pitch=0,IPCName='ALUMINUM_CAP',JEDECName='',YamahaName='',MirtecAoiClass='ALUMINUM_CAP',Description='Aluminum Electrolytic Capacitor',Notes='Nominal diameter and height. Verify pad geometry against manufacturer package drawing.' WHERE PackageName IN(SELECT PackageName FROM SpecialPassiveSeed);
INSERT OR IGNORE INTO PackageDefinition(PackageName,DisplayName,StandardName,PackageFamily,ComponentType,CategoryId,FamilyId,Length,Width,Height,BodyLength,BodyWidth,LeadCount,PadCount,Pitch,IPCName,JEDECName,YamahaName,MirtecAoiClass,Description,Notes,IsActive,CreatedAt,UpdatedAt) SELECT s.PackageName,s.PackageName,s.PackageName,'ALUMINUM_CAP','Capacitor',c.Id,f.Id,s.BodyLength,s.BodyWidth,s.Height,s.BodyLength,s.BodyWidth,2,2,0,'ALUMINUM_CAP','','','ALUMINUM_CAP','Aluminum Electrolytic Capacitor','Nominal diameter and height. Verify pad geometry against manufacturer package drawing.',1,datetime('now'),datetime('now') FROM SpecialPassiveSeed s JOIN PackageFamily f ON f.Code='ALUMINUM_CAP' JOIN PackageCategory c ON c.Id=f.CategoryId;
INSERT INTO MasterLibrary_PackageAliases(PackageId,Alias,AliasType,Source) SELECT Id,'ALC5X7','Geometry','Special passive seed 023' FROM PackageDefinition WHERE PackageName='ALC5-7.0H' AND NOT EXISTS(SELECT 1 FROM MasterLibrary_PackageAliases a WHERE a.PackageId=PackageDefinition.Id AND lower(a.Alias)=lower('ALC5X7'));
INSERT INTO MasterLibrary_PackageAliases(PackageId,Alias,AliasType,Source) SELECT Id,'ALC5-7H','Geometry','Special passive seed 023' FROM PackageDefinition WHERE PackageName='ALC5-7.0H' AND NOT EXISTS(SELECT 1 FROM MasterLibrary_PackageAliases a WHERE a.PackageId=PackageDefinition.Id AND lower(a.Alias)=lower('ALC5-7H'));
DROP TABLE SpecialPassiveSeed;
