ALTER TABLE PackageFootprint ADD COLUMN SourceSystem TEXT NOT NULL DEFAULT '';
ALTER TABLE PackageFootprint ADD COLUMN SourceUrl TEXT NOT NULL DEFAULT '';
ALTER TABLE PackageFootprint ADD COLUMN SourceMpn TEXT NOT NULL DEFAULT '';
ALTER TABLE PackageFootprint ADD COLUMN SourceVariant TEXT NOT NULL DEFAULT '';
ALTER TABLE PackageFootprint ADD COLUMN VerificationStatus TEXT NOT NULL DEFAULT '';
