<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.10" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Vega.StencilWorkflow\Vega.StencilWorkflow.csproj" />
    <ProjectReference Include="..\Vega.StencilCAM\Vega.StencilCAM.csproj" />
    <ProjectReference Include="..\Vega.CAD\Vega.CAD.csproj" />
  </ItemGroup>
</Project>