<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="ViewModels\" />
    <Folder Include="Resources\" />
    <Folder Include="Styles\" />
    <Folder Include="Converters\" />
    <Folder Include="Controls\" />
    <Folder Include="Dialogs\" />
    <Folder Include="Themes\" />
    <Folder Include="Images\" />
  </ItemGroup>

</Project>
