<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.10" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Vega.Models\Vega.Models.csproj" />
    <ProjectReference Include="..\Vega.Data\Vega.Data.csproj" />
    <ProjectReference Include="..\Vega.TechnologyDecision\Vega.TechnologyDecision.csproj" />
    <ProjectReference Include="..\Vega.StencilHistory\Vega.StencilHistory.csproj" />
    <ProjectReference Include="..\Vega.Report\Vega.Report.csproj" />
  </ItemGroup>
</Project>