<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Vega.CAD\Vega.CAD.csproj" />
    <ProjectReference Include="..\Vega.Models\Vega.Models.csproj" />
    <ProjectReference Include="..\Vega.Services\Vega.Services.csproj" />
  </ItemGroup>

</Project>
