<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Logging\" />
    <Folder Include="Configuration\" />
    <Folder Include="Import\" />
    <Folder Include="Export\" />
    <Folder Include="Update\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Vega.Data\Vega.Data.csproj" />
    <ProjectReference Include="..\Vega.PnP\Vega.PnP.csproj" />
    <ProjectReference Include="..\Vega.PackageRecognition\Vega.PackageRecognition.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.2.0" />
  </ItemGroup>
</Project>
