using System.Globalization;
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Spreadsheet;
using Vega.Models.MasterLibrary;
namespace Vega.Services.MasterLibrary.Import;
public enum PackageImportAction { Create, Update, Skip }
public enum PackageImportStatus { OK, Warning, Error }
public enum PackageImportMode { CreateOnly, CreateAndUpdate }
public sealed class PackageImportRow { public int RowNumber { get; init; } public Dictionary<string,string> Values { get; }=new(StringComparer.OrdinalIgnoreCase); public PackageDefinition? Package {get;internal set;} public List<string> Aliases {get;internal set;}=[]; }
public sealed class PackageImportMapping { public string SourceColumn {get;set;}=""; public string TargetField {get;set;}=""; }
public sealed class PackageImportValidationResult { public int RowNumber {get;init;} public string PackageName {get;init;}=""; public string PackageFamily {get;init;}=""; public PackageImportStatus Status {get;set;} public PackageImportAction Action {get;set;} public List<string> Messages {get;}=[]; public PackageImportRow Row {get;init;}=new(); }
public sealed class PackageImportResult { public int Imported {get;set;} public int Updated {get;set;} public int Skipped {get;set;} public List<PackageImportValidationResult> Errors {get;}=[]; }
public sealed class PackageImportDocument { public string FileName {get;init;}=""; public List<string> Sheets {get;}=[]; public List<string> Headers {get;}=[]; public List<PackageImportRow> Rows {get;}=[]; }
public sealed class PackageImportService
{
 public static readonly string[] Fields=["PackageName","StandardName","DisplayName","PackageFamily","ComponentType","Length","Width","Height","BodyLength","BodyWidth","LeadCount","PadCount","Pitch","LeadLength","LeadWidth","ThermalPadLength","ThermalPadWidth","BallDiameter","BallPitch","IPCName","JEDECName","YamahaName","MirtecAoiClass","Description","Notes","Aliases"];
 readonly PackageDefinitionService _service; public PackageImportService():this(new()){} public PackageImportService(PackageDefinitionService service)=>_service=service;
 public PackageImportDocument Load(string file,string? sheet=null)=>Path.GetExtension(file).ToLowerInvariant() switch {".csv"=>Csv(file),".xlsx"=>Xlsx(file,sheet),_=>throw new NotSupportedException("Only CSV and XLSX files are supported.")};
 public List<string> GetSheets(string file){if(!Path.GetExtension(file).Equals(".xlsx",StringComparison.OrdinalIgnoreCase))return[];using var d=SpreadsheetDocument.Open(file,false);return d.WorkbookPart!.Workbook.Sheets!.Elements<Sheet>().Select(x=>x.Name!.Value!).ToList();}
 public List<PackageImportMapping> AutoMap(IEnumerable<string> headers)=>headers.Select(x=>new PackageImportMapping{SourceColumn=x,TargetField=Map(x)}).ToList();
 public List<PackageImportValidationResult> Validate(IEnumerable<PackageImportRow> rows,IEnumerable<PackageImportMapping> maps,PackageImportMode mode,string unit="mm"){var m=maps.Where(x=>x.TargetField.Length>0).ToDictionary(x=>x.TargetField,x=>x.SourceColumn,StringComparer.OrdinalIgnoreCase);var all=_service.GetAll();return rows.Select(r=>ValidateRow(r,m,all,mode,unit)).ToList();}
 public PackageImportResult Import(IEnumerable<PackageImportValidationResult> rows){var outp=new PackageImportResult();foreach(var row in rows){if(row.Status==PackageImportStatus.Error||row.Action==PackageImportAction.Skip){outp.Skipped++;if(row.Status==PackageImportStatus.Error)outp.Errors.Add(row);continue;}try{var p=row.Row.Package!;if(row.Action==PackageImportAction.Create){p=_service.CreatePackage(p);outp.Imported++;}else{_service.Update(p);outp.Updated++;}var existing=_service.GetAliases(p.Id).Select(x=>x.Alias).ToHashSet(StringComparer.OrdinalIgnoreCase);foreach(var a in row.Row.Aliases.Where(existing.Add))_service.CreateAlias(new PackageAlias{PackageId=p.Id,Alias=a,AliasType="Import"});}catch(Exception ex){row.Status=PackageImportStatus.Error;row.Messages.Add(ex.Message);outp.Errors.Add(row);outp.Skipped++;}}return outp;}
 public void ExportTemplate(string file){using var d=SpreadsheetDocument.Create(file,SpreadsheetDocumentType.Workbook);var wb=d.AddWorkbookPart();wb.Workbook=new Workbook();Sheet(wb,"Packages",[Fields]);var x=new string[Fields.Length];x[0]="R0603";x[1]="IEC 0603";x[2]="Resistor 0603";x[3]="CHIP";x[4]="Resistor";x[5]="1.600";x[6]="0.800";x[7]="0.550";x[10]="2";x[12]="0.800";x[^1]="0603;1608;RES_0603";Sheet(wb,"Example",[Fields,x]);wb.Workbook.Save();}
 PackageImportValidationResult ValidateRow(PackageImportRow row,Dictionary<string,string> map,List<PackageDefinition> all,PackageImportMode mode,string unit){string G(string n)=>map.TryGetValue(n,out var s)&&row.Values.TryGetValue(s,out var v)?v.Trim():"";var p=new PackageDefinition{PackageName=G("PackageName"),StandardName=G("StandardName"),DisplayName=G("DisplayName"),PackageFamily=G("PackageFamily"),ComponentType=G("ComponentType"),IPCName=G("IPCName"),JEDECName=G("JEDECName"),YamahaName=G("YamahaName"),MirtecAoiClass=G("MirtecAoiClass"),Description=G("Description"),Notes=G("Notes")};var errors=new List<string>();SetDouble("Length",x=>p.Length=x);SetDouble("Width",x=>p.Width=x);SetDouble("Height",x=>p.Height=x);SetDouble("BodyLength",x=>p.BodyLength=x);SetDouble("BodyWidth",x=>p.BodyWidth=x);SetDouble("Pitch",x=>p.Pitch=x);SetDouble("LeadLength",x=>p.LeadLength=x);SetDouble("LeadWidth",x=>p.LeadWidth=x);SetDouble("ThermalPadLength",x=>p.ThermalPadLength=x);SetDouble("ThermalPadWidth",x=>p.ThermalPadWidth=x);SetDouble("BallDiameter",x=>p.BallDiameter=x);SetDouble("BallPitch",x=>p.BallPitch=x);SetInt("LeadCount",x=>p.LeadCount=x);SetInt("PadCount",x=>p.PadCount=x);void SetDouble(string n,Action<double> set){var raw=G(n);if(raw.Length==0)return;if(!double.TryParse(raw.Replace(" ","").Replace(',','.'),NumberStyles.Float,CultureInfo.InvariantCulture,out var v))errors.Add($"{n} is not a number.");else set(unit.Equals("inch",StringComparison.OrdinalIgnoreCase)?v*25.4:v);}void SetInt(string n,Action<int> set){var raw=G(n);if(raw.Length==0)return;if(!int.TryParse(raw,out var v)||v<0)errors.Add($"{n} must be a non-negative integer.");else set(v);}row.Aliases=G("Aliases").Split([';','|'],StringSplitOptions.RemoveEmptyEntries|StringSplitOptions.TrimEntries).Distinct(StringComparer.OrdinalIgnoreCase).ToList();row.Package=p;var old=all.FirstOrDefault(x=>x.PackageName.Equals(p.PackageName,StringComparison.OrdinalIgnoreCase));if(old!=null){p.Id=old.Id;p.CategoryId=old.CategoryId;p.FamilyId=old.FamilyId;}errors.AddRange(_service.ValidatePackage(p).Errors);var action=old==null?PackageImportAction.Create:mode==PackageImportMode.CreateAndUpdate?PackageImportAction.Update:PackageImportAction.Skip;if(action==PackageImportAction.Skip)errors.Add("PackageName already exists.");var result=new PackageImportValidationResult{RowNumber=row.RowNumber,PackageName=p.PackageName,PackageFamily=p.PackageFamily,Action=action,Status=errors.Count>0&&action!=PackageImportAction.Skip?PackageImportStatus.Error:action==PackageImportAction.Skip?PackageImportStatus.Warning:PackageImportStatus.OK,Row=row};result.Messages.AddRange(errors);return result;}
 static string Map(string h){var k=new string(h.Trim().ToUpperInvariant().Where(char.IsLetterOrDigit).ToArray());var a=new Dictionary<string,string>{{"PACKAGE","PackageName"},{"PACKAGENAME","PackageName"},{"КОРПУС","PackageName"},{"FAMILY","PackageFamily"},{"PACKAGEFAMILY","PackageFamily"},{"PITCH","Pitch"},{"PINPITCH","Pitch"},{"ШАГВЫВОДОВ","Pitch"},{"HEIGHT","Height"},{"H","Height"},{"ALIAS","Aliases"},{"ALIASES","Aliases"},{"ALTERNATIVENAMES","Aliases"}};return a.TryGetValue(k,out var r)?r:Fields.FirstOrDefault(x=>x.Equals(h.Trim(),StringComparison.OrdinalIgnoreCase))??"";}
 static PackageImportDocument Csv(string f){var lines=File.ReadAllLines(f);var d=new PackageImportDocument{FileName=f};if(lines.Length==0)return d;var h=Split(lines[0]);d.Headers.AddRange(h);for(var i=1;i<lines.Length;i++){if(string.IsNullOrWhiteSpace(lines[i]))continue;var r=new PackageImportRow{RowNumber=i+1};var values=Split(lines[i]);for(var c=0;c<h.Count;c++)r.Values[h[c]]=c<values.Count?values[c]:"";d.Rows.Add(r);}return d;}static List<string> Split(string line){var r=new List<string>();var b=new System.Text.StringBuilder();var q=false;foreach(var c in line){if(c=='"')q=!q;else if(c==','&&!q){r.Add(b.ToString());b.Clear();}else b.Append(c);}r.Add(b.ToString());return r;}
 static PackageImportDocument Xlsx(string f,string? wanted){using var d=SpreadsheetDocument.Open(f,false);var wb=d.WorkbookPart!;var sheets=wb.Workbook.Sheets!.Elements<Sheet>().ToList();var s=sheets.FirstOrDefault(x=>x.Name!.Value!.Equals(wanted,StringComparison.OrdinalIgnoreCase))??sheets.First();var ws=(WorksheetPart)wb.GetPartById(s.Id!);var rows=ws.Worksheet.Descendants<Row>().ToList();var o=new PackageImportDocument{FileName=f};o.Sheets.AddRange(sheets.Select(x=>x.Name!.Value!));if(rows.Count==0)return o;var shared=wb.SharedStringTablePart?.SharedStringTable;string V(Cell c){var v=c.CellValue?.InnerText??"";if(c.DataType?.Value==CellValues.InlineString)return c.InlineString?.Text?.Text??c.InlineString?.InnerText??"";return c.DataType?.Value==CellValues.SharedString&&int.TryParse(v,out var i)?shared?.ElementAt(i).InnerText??"":v;}var headers=rows[0].Elements<Cell>().Select(V).ToList();o.Headers.AddRange(headers);foreach(var source in rows.Skip(1)){var r=new PackageImportRow{RowNumber=(int)(source.RowIndex?.Value??0)};var cells=source.Elements<Cell>().ToList();for(var i=0;i<headers.Count;i++)r.Values[headers[i]]=i<cells.Count?V(cells[i]):"";o.Rows.Add(r);}return o;}
 static void Sheet(WorkbookPart wb,string name,IEnumerable<string[]> values){var part=wb.AddNewPart<WorksheetPart>();var data=new SheetData();foreach(var valuesRow in values){var r=new Row();foreach(var v in valuesRow)r.Append(new Cell{DataType=CellValues.InlineString,InlineString=new InlineString(new Text(v))});data.Append(r);}part.Worksheet=new Worksheet(data);var sheets=wb.Workbook.Sheets??wb.Workbook.AppendChild(new Sheets());sheets.Append(new Sheet{Id=wb.GetIdOfPart(part),SheetId=(uint)(sheets.Count()+1),Name=name});}
}
