using Vega.Data.MasterLibrary.Database;
using Vega.Services.MasterLibrary.Import;
using Xunit;
namespace Vega.Tests.MasterLibrary;
public sealed class PackageImportTests
{
 static PackageImportService Service(){MasterLibraryMigrationRunner.Apply();return new();}
 static PackageImportRow Row(string name="IMP_TEST"){var r=new PackageImportRow{RowNumber=2};r.Values["PackageName"]=name;r.Values["DisplayName"]=name;r.Values["PackageFamily"]="CHIP";r.Values["ComponentType"]="Resistor";return r;}
 [Fact] public void AutoColumnMapping(){var map=Service().AutoMap(["Package Name","Family","Pin Pitch","Aliases"]);Assert.Equal("PackageName",map[0].TargetField);Assert.Equal("PackageFamily",map[1].TargetField);Assert.Equal("Pitch",map[2].TargetField);Assert.Equal("Aliases",map[3].TargetField);}
 [Fact] public void CsvImportLoad(){var f=Path.ChangeExtension(Path.GetTempFileName(),".csv");File.WriteAllText(f,"PackageName,DisplayName,PackageFamily,ComponentType\nIMP_CSV,Test,CHIP,Resistor");var d=Service().Load(f);Assert.Single(d.Rows);Assert.Equal("IMP_CSV",d.Rows[0].Values["PackageName"]);File.Delete(f);}
 [Fact] public void XlsxTemplateLoad(){var f=Path.ChangeExtension(Path.GetTempFileName(),".xlsx");Service().ExportTemplate(f);var d=Service().Load(f,"Example");Assert.Contains("Example",d.Sheets);Assert.Equal("R0603",d.Rows[0].Values["PackageName"]);File.Delete(f);}
 [Theory][InlineData("1.25",1.25)][InlineData("1,25",1.25)] public void DecimalParsing(string source,double expected){var row=Row("IMP_DEC_"+Guid.NewGuid().ToString("N"));row.Values["Pitch"]=source;var result=Service().Validate([row],[new PackageImportMapping{SourceColumn="PackageName",TargetField="PackageName"},new PackageImportMapping{SourceColumn="DisplayName",TargetField="DisplayName"},new PackageImportMapping{SourceColumn="PackageFamily",TargetField="PackageFamily"},new PackageImportMapping{SourceColumn="ComponentType",TargetField="ComponentType"},new PackageImportMapping{SourceColumn="Pitch",TargetField="Pitch"}],PackageImportMode.CreateOnly).Single();Assert.Equal(PackageImportStatus.OK,result.Status);Assert.Equal(expected,result.Row.Package!.Pitch);}
 [Fact] public void AliasParsingAndDryRun(){var service=Service();var before=service.Validate([Row("IMP_ALIAS_"+Guid.NewGuid().ToString("N"))],[new PackageImportMapping{SourceColumn="PackageName",TargetField="PackageName"},new PackageImportMapping{SourceColumn="DisplayName",TargetField="DisplayName"},new PackageImportMapping{SourceColumn="PackageFamily",TargetField="PackageFamily"},new PackageImportMapping{SourceColumn="ComponentType",TargetField="ComponentType"}],PackageImportMode.CreateOnly);var r=before.Single();r.Row.Values["Aliases"]="0603; 1608|0603";var checkedRow=service.Validate([r.Row],[new PackageImportMapping{SourceColumn="PackageName",TargetField="PackageName"},new PackageImportMapping{SourceColumn="DisplayName",TargetField="DisplayName"},new PackageImportMapping{SourceColumn="PackageFamily",TargetField="PackageFamily"},new PackageImportMapping{SourceColumn="ComponentType",TargetField="ComponentType"},new PackageImportMapping{SourceColumn="Aliases",TargetField="Aliases"}],PackageImportMode.CreateOnly).Single();Assert.Equal(["0603","1608"],checkedRow.Row.Aliases);}
 [Fact] public void UnknownFamilyAndNegativeDimensionReject(){var row=Row("IMP_BAD_"+Guid.NewGuid().ToString("N"));row.Values["PackageFamily"]="UNKNOWN";row.Values["Length"]="-1";var result=Service().Validate([row],[new PackageImportMapping{SourceColumn="PackageName",TargetField="PackageName"},new PackageImportMapping{SourceColumn="DisplayName",TargetField="DisplayName"},new PackageImportMapping{SourceColumn="PackageFamily",TargetField="PackageFamily"},new PackageImportMapping{SourceColumn="ComponentType",TargetField="ComponentType"},new PackageImportMapping{SourceColumn="Length",TargetField="Length"}],PackageImportMode.CreateOnly).Single();Assert.Equal(PackageImportStatus.Error,result.Status);}
}
