<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Context\" />
    <Folder Include="Import\" />
    <Folder Include="Export\" />
    <Folder Include="MasterLibrary\Новая папка\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Vega.Models\Vega.Models.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Migration\001_MasterLibrary.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>

    <None Update="Migration\002_MasterLibrary_Packages.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>

    <None Update="Migration\003_MasterLibrary_Components.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>

    <None Update="Migration\004_MasterLibrary_PackageGeometry.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Migration\005_MasterLibrary_PackageFootprint.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>