using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using Vega.Models.MasterLibrary;
using Vega.Services.MasterLibrary;

namespace Vega.StencilUI.ViewModels;
public enum PackageEditorMode { Create, Edit, Duplicate }
public sealed class PackageEditorViewModel : INotifyPropertyChanged
{
 private readonly PackageDefinitionService _service; private readonly PackageDefinition? _original; private bool _saved; private int _previewVersion;
 public PackageEditorViewModel(PackageEditorMode mode, PackageDefinition? package = null) : this(new PackageDefinitionService(),mode,package) { }
 public PackageEditorViewModel(PackageDefinitionService service, PackageEditorMode mode, PackageDefinition? package = null)
 { _service=service; Mode=mode; Families=new ObservableCollection<string>(_service.GetAll().Select(p=>p.PackageFamily).Where(x=>!string.IsNullOrWhiteSpace(x)).Distinct(StringComparer.OrdinalIgnoreCase).OrderBy(x=>x)); ComponentTypes=new ObservableCollection<string>(Types); WorkingCopy=mode==PackageEditorMode.Create ? CreateDefault() : Copy(package ?? throw new ArgumentNullException(nameof(package))); _original=package; if(package is not null) foreach(var a in _service.GetAliases(package.Id)) Aliases.Add(Copy(a)); }
 public static readonly string[] Types=["Resistor","Capacitor","Inductor","Diode","Transistor","MOSFET","IC","Connector","LED","Crystal","Oscillator","Transformer","Relay","Other"];
 public PackageEditorMode Mode {get;} public PackageDefinition WorkingCopy {get; private set;} public ObservableCollection<string> Families {get;} public ObservableCollection<string> ComponentTypes {get;} public ObservableCollection<PackageAlias> Aliases {get;}=[]; public ObservableCollection<string> Errors {get;}=[];
 public bool IsDirty {get; private set;} public bool IsSaved=>_saved; public string Title=>$"{Mode} Package";
 public string PackageName {get=>WorkingCopy.PackageName;set=>SetPackage(p=>p.PackageName=value);} public string StandardName {get=>WorkingCopy.StandardName;set=>SetPackage(p=>p.StandardName=value);} public string DisplayName {get=>WorkingCopy.DisplayName;set=>SetPackage(p=>p.DisplayName=value);} public string PackageFamily {get=>WorkingCopy.PackageFamily;set=>SetPackage(p=>p.PackageFamily=value);} public string ComponentType {get=>WorkingCopy.ComponentType;set=>SetPackage(p=>p.ComponentType=value);} public string Description {get=>WorkingCopy.Description;set=>SetPackage(p=>p.Description=value);} public string Notes {get=>WorkingCopy.Notes;set=>SetPackage(p=>p.Notes=value);} public string IPCName {get=>WorkingCopy.IPCName;set=>SetPackage(p=>p.IPCName=value);} public string JEDECName {get=>WorkingCopy.JEDECName;set=>SetPackage(p=>p.JEDECName=value);} public string YamahaName {get=>WorkingCopy.YamahaName;set=>SetPackage(p=>p.YamahaName=value);} public string MirtecAoiClass {get=>WorkingCopy.MirtecAoiClass;set=>SetPackage(p=>p.MirtecAoiClass=value);}
 public double Length {get=>WorkingCopy.Length;set=>SetPackage(p=>p.Length=value);} public double Width {get=>WorkingCopy.Width;set=>SetPackage(p=>p.Width=value);} public double Height {get=>WorkingCopy.Height;set=>SetPackage(p=>p.Height=value);} public double BodyLength {get=>WorkingCopy.BodyLength;set=>SetPackage(p=>p.BodyLength=value);} public double BodyWidth {get=>WorkingCopy.BodyWidth;set=>SetPackage(p=>p.BodyWidth=value);} public int LeadCount {get=>WorkingCopy.LeadCount;set=>SetPackage(p=>p.LeadCount=value);} public int PadCount {get=>WorkingCopy.PadCount;set=>SetPackage(p=>p.PadCount=value);} public double Pitch {get=>WorkingCopy.Pitch;set=>SetPackage(p=>p.Pitch=value);} public double LeadLength {get=>WorkingCopy.LeadLength;set=>SetPackage(p=>p.LeadLength=value);} public double LeadWidth {get=>WorkingCopy.LeadWidth;set=>SetPackage(p=>p.LeadWidth=value);} public double ThermalPadLength {get=>WorkingCopy.ThermalPadLength;set=>SetPackage(p=>p.ThermalPadLength=value);} public double ThermalPadWidth {get=>WorkingCopy.ThermalPadWidth;set=>SetPackage(p=>p.ThermalPadWidth=value);} public double BallDiameter {get=>WorkingCopy.BallDiameter;set=>SetPackage(p=>p.BallDiameter=value);} public double BallPitch {get=>WorkingCopy.BallPitch;set=>SetPackage(p=>p.BallPitch=value);}
 public PackageDefinition PreviewPackage=>WorkingCopy; public int PreviewVersion => _previewVersion;
 public bool ShowLeadFields => Is("SOT","SOIC","SOP","SSOP","TSSOP","MSOP","TSOP","QFP","LQFP","TQFP","DPAK","D2PAK","D3PAK");
 public bool ShowThermalFields => Is("QFN","DFN","SON") || (WorkingCopy.ThermalPadLength > 0 || WorkingCopy.ThermalPadWidth > 0);
 public bool ShowBallFields => Is("BGA","FBGA","CSP","WLCSP","LGA");
 private bool Is(params string[] families) => families.Contains(WorkingCopy.PackageFamily, StringComparer.OrdinalIgnoreCase);
 public bool Save(){Errors.Clear(); AssignFamilyIds(); var r=_service.ValidatePackage(WorkingCopy); foreach(var e in r.Errors)Errors.Add(e); if(!r.IsValid)return false; if(WorkingCopy.Id==0){WorkingCopy=_service.CreatePackage(WorkingCopy);foreach(var a in Aliases.Where(a=>a.Id==0)){a.PackageId=WorkingCopy.Id;var saved=_service.CreateAlias(a);a.Id=saved.Id;}}else { _service.Update(WorkingCopy); foreach(var a in Aliases.Where(a=>a.Id==0)){a.PackageId=WorkingCopy.Id;var saved=_service.CreateAlias(a);a.Id=saved.Id;} } _saved=true;IsDirty=false;Raise(nameof(IsSaved));Raise(nameof(IsDirty));return true;}
 public void AddAlias(string alias,string type="",string notes="") { if(!string.IsNullOrWhiteSpace(alias)){Aliases.Add(new PackageAlias{PackageId=WorkingCopy.Id,Alias=alias.Trim(),AliasType=type,Source=notes});IsDirty=true;Raise(nameof(IsDirty));}}
 public void RemoveAlias(PackageAlias alias){if(alias.Id>0)_service.DeleteAlias(alias.Id);Aliases.Remove(alias);IsDirty=true;Raise(nameof(IsDirty));}
 private PackageDefinition CreateDefault(){var p=_service.GetAll().FirstOrDefault();return new PackageDefinition{PackageName="",DisplayName="",PackageFamily=p?.PackageFamily??"CHIP",ComponentType="Other",CategoryId=p?.CategoryId??1,FamilyId=p?.FamilyId??1};}
 private void AssignFamilyIds(){var match=_service.GetAll().FirstOrDefault(p=>p.PackageFamily.Equals(WorkingCopy.PackageFamily,StringComparison.OrdinalIgnoreCase));if(match is not null){WorkingCopy.CategoryId=match.CategoryId;WorkingCopy.FamilyId=match.FamilyId;}}
 private void SetPackage(Action<PackageDefinition> set,[CallerMemberName]string? name=null){set(WorkingCopy);IsDirty=true;Raise(name!);_previewVersion++;Raise(nameof(PreviewPackage));Raise(nameof(PreviewVersion));Raise(nameof(ShowLeadFields));Raise(nameof(ShowThermalFields));Raise(nameof(ShowBallFields));Raise(nameof(IsDirty));}
 private static PackageDefinition Copy(PackageDefinition p){var c=new PackageDefinition();foreach(var x in typeof(PackageDefinition).GetProperties().Where(x=>x.CanRead&&x.CanWrite))x.SetValue(c,x.GetValue(p));return c;} private static PackageAlias Copy(PackageAlias a)=>new(){Id=a.Id,PackageId=a.PackageId,Alias=a.Alias,AliasType=a.AliasType,Source=a.Source,IsActive=a.IsActive}; public event PropertyChangedEventHandler? PropertyChanged;private void Raise(string n)=>PropertyChanged?.Invoke(this,new(n));
}