<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Vega.StencilWorkflow\Vega.StencilWorkflow.csproj" />
    <ProjectReference Include="..\Vega.StencilProject\Vega.StencilProject.csproj" />
    <ProjectReference Include="..\Vega.StencilViewer\Vega.StencilViewer.csproj" />
    <ProjectReference Include="..\Vega.StencilInput\Vega.StencilInput.csproj" />
    <ProjectReference Include="..\Vega.StencilCAM\Vega.StencilCAM.csproj" />
    <ProjectReference Include="..\Vega.Gerber\Vega.Gerber.csproj" />
    <ProjectReference Include="..\Vega.CAD\Vega.CAD.csproj" />
    <ProjectReference Include="..\Vega.EngineeringDashboard\Vega.EngineeringDashboard.csproj" />
    <ProjectReference Include="..\Vega.Report\Vega.Report.csproj" />
    <ProjectReference Include="..\Vega.Localization\Vega.Localization.csproj" />
    <ProjectReference Include="..\Vega.TechnologyDecision\Vega.TechnologyDecision.csproj" />
    <ProjectReference Include="..\Vega.StencilHistory\Vega.StencilHistory.csproj" />
    <ProjectReference Include="..\Vega.Services\Vega.Services.csproj" />
    <ProjectReference Include="..\Vega.Models\Vega.Models.csproj" />
    <ProjectReference Include="..\Vega.Infrastructure\Vega.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\Images\Vega-SMD-Logo.jpg" />
    <Resource Include="Assets\Approved\*.png" />
    <None Include="Assets\components\**\*.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Assets\components_images.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Assets\KiCad-LICENSE.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Assets\Manufacturer\Infineon\PG-SOT23-3-4-Package-Outline.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Manufacturer\**\*.step">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Reference\**\*.step">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Assets\Manufacturer\**\*.stp">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <Content Include="Assets\Generated\*.glb" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
